name: Run Selenium Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Set the Java version you need
          distribution: 'adopt'

      - name: Set execute permission for gradlew
        run: chmod +x path/to/your/project/gradlew
        working-directory: ${{ github.workspace }}/path/to/your/project

      - name: Build and Run Selenium Test
        run: |
            ./gradlew test
        working-directory: ${{ github.workspace }}
