name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set execute permission for gradlew
      run: chmod +x selenium-kotlin-fw/gradlew
      working-directory: ${{ github.workspace }}/selenium-kotlin-fw

    - name: Build and Run Selenium Test
      run: |
        cd selenium-kotlin-fw
        ./gradlew test
      working-directory: ${{ github.workspace }}
